[package]
name = "space_editor"
version = "0.1.0"
edition = "2021"
default-run = "space_editor"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.11"
bevy_egui = "0.21"
egui-gizmo = "0.11.0"
bevy-scene-hook = "7"